### PR TITLE
Wallet/feature 400

### PR DESCRIPTION
**Pull request by autholykos**

### CODE REVIEW

**Comment by autholykos** [comment]
> It looks like the `block` package was not migrated yet.

I understand now what you meant with migrating `block` package. I see Travis failing because of that. However, I don't understand how this is happening since 1) on my machine everything seems to run just fine (with the same `golangci.yml` configuration and 2) the offending package `pkg/core/data/block` is regularly found in the codebase

**Comment by julesdesmit** [comment]
> the offending package pkg/core/data/block is regularly found in the codebase

It seems not, for me anyways.
Screenshot 2020-04-14 at 08 36 05
Screenshot 2020-04-14 at 08 35 30

**Comment by autholykos** [comment]
Screenshot 2020-04-14 at 08 38 14

Weird. There is nothing in my `.gitignore` to prevent `pkg/core/data/block` to be regularly added and committed

**Comment by julesdesmit** [comment]
@autholykos I think I might know what it is - I had struggled with something similar when I was migrating the `block` out of this repo. In `.gitignore`, there's a line `*LOCK` which I believe might be the offender here. It's supposed to keep leveldb files out of the repo but it affects the block package inadvertently.

**Comment by autholykos** [comment]
Indeed that was the problem. A `git status --ignored` highlighted that indeed the package was ignored. I force added `block` package and it should be OK now. I will also modify the `*LOCK` entry on `.gitignore`, so to just pick the leveldb files

**Comment by autholykos** [comment]
actually, a better way is to change locally the `.git/config` to let git be case-sensitive:
```
...
[core]
    ignorecase = false
...
```
```

**Pull request merged**
